# Generated by Django 5.2.17 on 2026-09-22 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام چک\u200cلیست')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'الگوی چک\u200cلیست',
                'verbose_name_plural': 'الگوهای چک\u200cلیست',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته تجهیز',
                'verbose_name_plural': 'دسته\u200cهای تجهیز',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='مورد کنترل')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='راهنما')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.checklisttemplate')),
            ],
            options={
                'verbose_name': 'مورد چک\u200cلیست',
                'verbose_name_plural': 'موارد چک\u200cلیست',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد تجهیز')),
                ('name', models.CharField(max_length=160, verbose_name='نام تجهیز')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='محل استقرار')),
                ('operating_unit', models.CharField(blank=True, max_length=150, verbose_name='واحد بهره\u200cبردار')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='سازنده')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='شماره سریال')),
                ('capacity', models.CharField(blank=True, max_length=100, verbose_name='ظرفیت')),
                ('criticality', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بحرانی')], default='medium', max_length=10, verbose_name='درجه اهمیت')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('out', 'خارج از سرویس'), ('stopped', 'متوقف')], default='active', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.equipmentcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'تجهیز',
                'verbose_name_plural': 'تجهیزات',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipmentcategory', verbose_name='دسته تجهیز'),
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'تأیید شد'), ('issue', 'مشکل دارد'), ('action', 'نیاز به اقدام'), ('na', 'قابل بررسی نبود')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='maintenance.inspection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.checklistitem')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('semiannual', 'شش\u200cماهه'), ('annual', 'سالانه')], max_length=20, verbose_name='تناوب')),
                ('next_due_date', models.DateField(verbose_name='تاریخ سرویس بعدی')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.checklisttemplate', verbose_name='چک\u200cلیست')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment', verbose_name='تجهیز')),
            ],
            options={
                'verbose_name': 'برنامه سرویس',
                'verbose_name_plural': 'برنامه\u200cهای سرویس',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceplan'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان درخواست')),
                ('description', models.TextField(verbose_name='شرح مشکل')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('urgent', 'اضطراری'), ('long', 'درازمدت')], default='normal', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('progress', 'در حال انجام'), ('done', 'تکمیل\u200cشده')], default='new', max_length=12, verbose_name='وضعیت')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان اعلام')),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='مدت توقف (ساعت)')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه تعمیرات')),
                ('action_taken', models.TextField(blank=True, verbose_name='اقدام انجام\u200cشده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اتمام')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.equipment', verbose_name='تجهیز')),
            ],
            options={
                'verbose_name': 'درخواست کار',
                'verbose_name_plural': 'درخواست\u200cهای کار',
                'ordering': ['-reported_at'],
            },
        ),
    ]
