# Generated by Django 5.2.17 on 2026-09-22 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentControlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='مورد کنترل')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='راهنما')),
                ('frequency', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('biweekly', 'هر دو هفته'), ('monthly', 'ماهانه'), ('bimonthly', 'هر دو ماه'), ('quarterly', 'سه\u200cماهه'), ('semiannual', 'شش\u200cماهه'), ('annual', 'سالانه')], default='monthly', max_length=20, verbose_name='تناوب انجام')),
                ('next_due_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ انجام بعدی')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_items', to='maintenance.equipment', verbose_name='تجهیز')),
            ],
            options={
                'verbose_name': 'مورد کنترل تجهیز',
                'verbose_name_plural': 'موارد کنترل تجهیزات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'تأیید شد'), ('issue', 'مشکل دارد'), ('action', 'نیاز به اقدام'), ('na', 'قابل بررسی نبود')], max_length=10, verbose_name='نتیجه')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('control_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='maintenance.equipmentcontrolitem', verbose_name='مورد کنترل')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.workorder', verbose_name='درخواست تعمیر ایجادشده')),
            ],
            options={
                'verbose_name': 'ثبت کنترل تجهیز',
                'verbose_name_plural': 'ثبت\u200cهای کنترل تجهیزات',
                'ordering': ['-performed_at'],
            },
        ),
    ]
