# Generated by Django 5.2.17 on 2026-09-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_copy_existing_plan_items_to_equipment_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='service_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام برنامه سرویس'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='frequency',
            field=models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('biweekly', 'هر دو هفته'), ('monthly', 'ماهانه'), ('bimonthly', 'هر دو ماه'), ('quarterly', 'سه\u200cماهه'), ('semiannual', 'شش\u200cماهه'), ('annual', 'سالانه')], max_length=20, verbose_name='تناوب'),
        ),
    ]
