# Generated by Django 5.2.17 on 2026-09-23 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenanceplan_service_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسئول انجام'),
        ),
        migrations.CreateModel(
            name='EquipmentSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='نام وسیله یا قطعه')),
                ('unit', models.CharField(default='عدد', max_length=30, verbose_name='واحد شمارش')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('minimum_quantity', models.PositiveIntegerField(default=1, verbose_name='حداقل موجودی مورد نیاز')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='maintenance.equipment', verbose_name='تجهیز')),
            ],
            options={
                'verbose_name': 'وسیله مورد نیاز تجهیز',
                'verbose_name_plural': 'وسایل مورد نیاز تجهیزات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSupplyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'افزایش موجودی'), ('consume', 'مصرف')], max_length=10, verbose_name='نوع عملیات')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='maintenance.equipmentsupply', verbose_name='وسیله')),
            ],
            options={
                'verbose_name': 'گردش موجودی تجهیز',
                'verbose_name_plural': 'گردش موجودی تجهیزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentsupply',
            constraint=models.UniqueConstraint(fields=('equipment', 'name'), name='unique_equipment_supply'),
        ),
    ]
